# A GitHub Actions workflow file to run on pull request events

name: Pull Request Checks
on: 
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  # -----------------------------------
  # Code Quality and Linting Checks
  # -----------------------------------
    check_code_quality:
      name: Code Quality & Linting Checks
      runs-on: ubuntu-latest

  # -----------------------------------
  # Install and Imports Checks
  # -----------------------------------
    install_and_import_checks:
      name: Install and Import Checks
      runs-on: ubuntu-latest

  # -----------------------------------
  # Unit Tests
  # -----------------------------------
  